# fly.toml app configuration file generated for iron-relax-discord-bot on 2023-10-05T10:46:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "iron-relax-discord-bot"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[processes]
  worker = "npm start"

[env]
  PORT = "8080"
  PRIMARY_REGION = "dfw"

[[vms]]
    size = "shared-cpu-1x"
    memory = "512mb"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["worker"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
